export const ErrorCodes = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  SESSION_EXPIRED: "SESSION_EXPIRED",
  FORBIDDEN: "FORBIDDEN",
  ROOM_NOT_FOUND: "ROOM_NOT_FOUND",
  ROOM_FULL: "ROOM_FULL",
  SEAT_TAKEN: "SEAT_TAKEN",
  NOT_IN_ROOM: "NOT_IN_ROOM",
  NOT_OWNER: "NOT_OWNER",
  NOT_SEATED: "NOT_SEATED",
  ROOM_NOT_WAITING: "ROOM_NOT_WAITING",
  ROOM_IN_MATCH: "ROOM_IN_MATCH",
  NOT_ALL_READY: "NOT_ALL_READY",
  ALREADY_STARTED: "ALREADY_STARTED",
  NOT_YOUR_TURN: "NOT_YOUR_TURN",
  INVALID_ACTION: "INVALID_ACTION",
  INSUFFICIENT_STACK: "INSUFFICIENT_STACK",
  STALE_TURN: "STALE_TURN",
  STALE_VERSION: "STALE_VERSION",
  IDEMPOTENT_REPLAY_OK: "IDEMPOTENT_REPLAY_OK",
  RECONNECT_EXPIRED: "RECONNECT_EXPIRED",
  SEAT_MISMATCH: "SEAT_MISMATCH",
  MATCH_NOT_FOUND: "MATCH_NOT_FOUND",
  MATCH_LOCKED: "MATCH_LOCKED",
  RATE_LIMITED: "RATE_LIMITED",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  ROOM_CREATE_FAILED: "ROOM_CREATE_FAILED",
};

const retryable = new Set([
  ErrorCodes.RATE_LIMITED,
  ErrorCodes.STALE_TURN,
  ErrorCodes.STALE_VERSION,
  ErrorCodes.NOT_ALL_READY,
  ErrorCodes.IDEMPOTENT_REPLAY_OK,
]);

export function makeError(code, message = code, extra = {}) {
  return {
    code,
    message,
    retryable: retryable.has(code),
    ...extra,
  };
}
