export const SITE_TITLE = 'lilnong.top - 李侬的个人站';
export const SITE_DESCRIPTION = '李侬的个人站 - 技术博客与思考';
export const SITE_AUTHOR = '李侬';
export const SITE_TAGLINE = '前端开发 · AI 实践 · 技术探索';
export const SITE_SUBTITLE = '用代码和 AI 构建有趣的东西';
export const BAIDU_HM_ID = '0b53b11d3930be87062f66b4b8ce2822';
export const GA_MEASUREMENT_ID = 'G-SZZNDW21W6';
export const GENERATE_SLUG_FROM_TITLE = false;
export const TRANSITION_API = true;
