// cocos/assets/Script/Core/Config.ts
// 本地默认配置兜底：60 关 + 65 卡 + 10 档难度。
// 由 scripts/gen-config.mjs 生成的 config/*.json 同步而来；
// 云端 config 返回失败/为空时，客户端用此配置保证游戏可运行。
export const DEFAULT_LEVELS = [
  {
    "id": "ch1_01",
    "chapterId": "ch1",
    "chapterName": "花语集·春",
    "seriesId": "flower",
    "indexInChapter": 1,
    "difficultyStars": 1,
    "pieceCount": 4,
    "stdTimeSec": 30,
    "shape": "rect",
    "refMode": "always",
    "rotatable": false,
    "rarity": "N"
  },
  {
    "id": "ch1_02",
    "chapterId": "ch1",
    "chapterName": "花语集·春",
    "seriesId": "flower",
    "indexInChapter": 2,
    "difficultyStars": 1,
    "pieceCount": 4,
    "stdTimeSec": 30,
    "shape": "rect",
    "refMode": "always",
    "rotatable": false,
    "rarity": "N"
  },
  {
    "id": "ch1_03",
    "chapterId": "ch1",
    "chapterName": "花语集·春",
    "seriesId": "flower",
    "indexInChapter": 3,
    "difficultyStars": 1,
    "pieceCount": 4,
    "stdTimeSec": 30,
    "shape": "rect",
    "refMode": "always",
    "rotatable": false,
    "rarity": "N"
  },
  {
    "id": "ch1_04",
    "chapterId": "ch1",
    "chapterName": "花语集·春",
    "seriesId": "flower",
    "indexInChapter": 4,
    "difficultyStars": 1,
    "pieceCount": 4,
    "stdTimeSec": 30,
    "shape": "rect",
    "refMode": "always",
    "rotatable": false,
    "rarity": "N"
  },
  {
    "id": "ch1_05",
    "chapterId": "ch1",
    "chapterName": "花语集·春",
    "seriesId": "flower",
    "indexInChapter": 5,
    "difficultyStars": 1,
    "pieceCount": 4,
    "stdTimeSec": 30,
    "shape": "rect",
    "refMode": "always",
    "rotatable": false,
    "rarity": "N"
  },
  {
    "id": "ch1_06",
    "chapterId": "ch1",
    "chapterName": "花语集·春",
    "seriesId": "flower",
    "indexInChapter": 6,
    "difficultyStars": 1,
    "pieceCount": 4,
    "stdTimeSec": 30,
    "shape": "rect",
    "refMode": "always",
    "rotatable": false,
    "rarity": "N"
  },
  {
    "id": "ch1_07",
    "chapterId": "ch1",
    "chapterName": "花语集·春",
    "seriesId": "flower",
    "indexInChapter": 7,
    "difficultyStars": 2,
    "pieceCount": 9,
    "stdTimeSec": 60,
    "shape": "rect",
    "refMode": "first5s",
    "rotatable": false,
    "rarity": "N"
  },
  {
    "id": "ch1_08",
    "chapterId": "ch1",
    "chapterName": "花语集·春",
    "seriesId": "flower",
    "indexInChapter": 8,
    "difficultyStars": 2,
    "pieceCount": 9,
    "stdTimeSec": 60,
    "shape": "rect",
    "refMode": "first5s",
    "rotatable": false,
    "rarity": "N"
  },
  {
    "id": "ch1_09",
    "chapterId": "ch1",
    "chapterName": "花语集·春",
    "seriesId": "flower",
    "indexInChapter": 9,
    "difficultyStars": 2,
    "pieceCount": 9,
    "stdTimeSec": 60,
    "shape": "rect",
    "refMode": "first5s",
    "rotatable": false,
    "rarity": "N"
  },
  {
    "id": "ch1_10",
    "chapterId": "ch1",
    "chapterName": "花语集·春",
    "seriesId": "flower",
    "indexInChapter": 10,
    "difficultyStars": 2,
    "pieceCount": 9,
    "stdTimeSec": 60,
    "shape": "rect",
    "refMode": "first5s",
    "rotatable": false,
    "rarity": "N"
  },
  {
    "id": "ch1_11",
    "chapterId": "ch1",
    "chapterName": "花语集·春",
    "seriesId": "flower",
    "indexInChapter": 11,
    "difficultyStars": 2,
    "pieceCount": 9,
    "stdTimeSec": 60,
    "shape": "rect",
    "refMode": "first5s",
    "rotatable": false,
    "rarity": "N"
  },
  {
    "id": "ch1_12",
    "chapterId": "ch1",
    "chapterName": "花语集·春",
    "seriesId": "flower",
    "indexInChapter": 12,
    "difficultyStars": 2,
    "pieceCount": 9,
    "stdTimeSec": 60,
    "shape": "rect",
    "refMode": "first5s",
    "rotatable": false,
    "rarity": "N"
  },
  {
    "id": "ch2_01",
    "chapterId": "ch2",
    "chapterName": "萌宠志·萌",
    "seriesId": "pet",
    "indexInChapter": 1,
    "difficultyStars": 3,
    "pieceCount": 16,
    "stdTimeSec": 90,
    "shape": "rounded",
    "refMode": "first5s",
    "rotatable": false,
    "rarity": "N"
  },
  {
    "id": "ch2_02",
    "chapterId": "ch2",
    "chapterName": "萌宠志·萌",
    "seriesId": "pet",
    "indexInChapter": 2,
    "difficultyStars": 3,
    "pieceCount": 16,
    "stdTimeSec": 90,
    "shape": "rounded",
    "refMode": "first5s",
    "rotatable": false,
    "rarity": "N"
  },
  {
    "id": "ch2_03",
    "chapterId": "ch2",
    "chapterName": "萌宠志·萌",
    "seriesId": "pet",
    "indexInChapter": 3,
    "difficultyStars": 3,
    "pieceCount": 16,
    "stdTimeSec": 90,
    "shape": "rounded",
    "refMode": "first5s",
    "rotatable": false,
    "rarity": "N"
  },
  {
    "id": "ch2_04",
    "chapterId": "ch2",
    "chapterName": "萌宠志·萌",
    "seriesId": "pet",
    "indexInChapter": 4,
    "difficultyStars": 3,
    "pieceCount": 16,
    "stdTimeSec": 90,
    "shape": "rounded",
    "refMode": "first5s",
    "rotatable": false,
    "rarity": "N"
  },
  {
    "id": "ch2_05",
    "chapterId": "ch2",
    "chapterName": "萌宠志·萌",
    "seriesId": "pet",
    "indexInChapter": 5,
    "difficultyStars": 3,
    "pieceCount": 16,
    "stdTimeSec": 90,
    "shape": "rounded",
    "refMode": "first5s",
    "rotatable": false,
    "rarity": "N"
  },
  {
    "id": "ch2_06",
    "chapterId": "ch2",
    "chapterName": "萌宠志·萌",
    "seriesId": "pet",
    "indexInChapter": 6,
    "difficultyStars": 3,
    "pieceCount": 16,
    "stdTimeSec": 90,
    "shape": "rounded",
    "refMode": "first5s",
    "rotatable": false,
    "rarity": "N"
  },
  {
    "id": "ch2_07",
    "chapterId": "ch2",
    "chapterName": "萌宠志·萌",
    "seriesId": "pet",
    "indexInChapter": 7,
    "difficultyStars": 4,
    "pieceCount": 25,
    "stdTimeSec": 120,
    "shape": "rounded",
    "refMode": "none",
    "rotatable": false,
    "rarity": "N"
  },
  {
    "id": "ch2_08",
    "chapterId": "ch2",
    "chapterName": "萌宠志·萌",
    "seriesId": "pet",
    "indexInChapter": 8,
    "difficultyStars": 4,
    "pieceCount": 25,
    "stdTimeSec": 120,
    "shape": "rounded",
    "refMode": "none",
    "rotatable": false,
    "rarity": "N"
  },
  {
    "id": "ch2_09",
    "chapterId": "ch2",
    "chapterName": "萌宠志·萌",
    "seriesId": "pet",
    "indexInChapter": 9,
    "difficultyStars": 4,
    "pieceCount": 25,
    "stdTimeSec": 120,
    "shape": "rounded",
    "refMode": "none",
    "rotatable": false,
    "rarity": "N"
  },
  {
    "id": "ch2_10",
    "chapterId": "ch2",
    "chapterName": "萌宠志·萌",
    "seriesId": "pet",
    "indexInChapter": 10,
    "difficultyStars": 4,
    "pieceCount": 25,
    "stdTimeSec": 120,
    "shape": "rounded",
    "refMode": "none",
    "rotatable": false,
    "rarity": "N"
  },
  {
    "id": "ch2_11",
    "chapterId": "ch2",
    "chapterName": "萌宠志·萌",
    "seriesId": "pet",
    "indexInChapter": 11,
    "difficultyStars": 4,
    "pieceCount": 25,
    "stdTimeSec": 120,
    "shape": "rounded",
    "refMode": "none",
    "rotatable": false,
    "rarity": "N"
  },
  {
    "id": "ch2_12",
    "chapterId": "ch2",
    "chapterName": "萌宠志·萌",
    "seriesId": "pet",
    "indexInChapter": 12,
    "difficultyStars": 4,
    "pieceCount": 25,
    "stdTimeSec": 120,
    "shape": "rounded",
    "refMode": "none",
    "rotatable": false,
    "rarity": "N"
  },
  {
    "id": "ch3_01",
    "chapterId": "ch3",
    "chapterName": "食光记·味",
    "seriesId": "food",
    "indexInChapter": 1,
    "difficultyStars": 5,
    "pieceCount": 36,
    "stdTimeSec": 150,
    "shape": "rounded",
    "refMode": "none",
    "rotatable": false,
    "rarity": "N"
  },
  {
    "id": "ch3_02",
    "chapterId": "ch3",
    "chapterName": "食光记·味",
    "seriesId": "food",
    "indexInChapter": 2,
    "difficultyStars": 5,
    "pieceCount": 36,
    "stdTimeSec": 150,
    "shape": "rounded",
    "refMode": "none",
    "rotatable": false,
    "rarity": "N"
  },
  {
    "id": "ch3_03",
    "chapterId": "ch3",
    "chapterName": "食光记·味",
    "seriesId": "food",
    "indexInChapter": 3,
    "difficultyStars": 5,
    "pieceCount": 36,
    "stdTimeSec": 150,
    "shape": "rounded",
    "refMode": "none",
    "rotatable": false,
    "rarity": "N"
  },
  {
    "id": "ch3_04",
    "chapterId": "ch3",
    "chapterName": "食光记·味",
    "seriesId": "food",
    "indexInChapter": 4,
    "difficultyStars": 5,
    "pieceCount": 36,
    "stdTimeSec": 150,
    "shape": "rounded",
    "refMode": "none",
    "rotatable": false,
    "rarity": "N"
  },
  {
    "id": "ch3_05",
    "chapterId": "ch3",
    "chapterName": "食光记·味",
    "seriesId": "food",
    "indexInChapter": 5,
    "difficultyStars": 5,
    "pieceCount": 36,
    "stdTimeSec": 150,
    "shape": "rounded",
    "refMode": "none",
    "rotatable": false,
    "rarity": "N"
  },
  {
    "id": "ch3_06",
    "chapterId": "ch3",
    "chapterName": "食光记·味",
    "seriesId": "food",
    "indexInChapter": 6,
    "difficultyStars": 5,
    "pieceCount": 36,
    "stdTimeSec": 150,
    "shape": "rounded",
    "refMode": "none",
    "rotatable": false,
    "rarity": "N"
  },
  {
    "id": "ch3_07",
    "chapterId": "ch3",
    "chapterName": "食光记·味",
    "seriesId": "food",
    "indexInChapter": 7,
    "difficultyStars": 6,
    "pieceCount": 49,
    "stdTimeSec": 200,
    "shape": "irregular",
    "refMode": "none",
    "rotatable": false,
    "rarity": "N"
  },
  {
    "id": "ch3_08",
    "chapterId": "ch3",
    "chapterName": "食光记·味",
    "seriesId": "food",
    "indexInChapter": 8,
    "difficultyStars": 6,
    "pieceCount": 49,
    "stdTimeSec": 200,
    "shape": "irregular",
    "refMode": "none",
    "rotatable": false,
    "rarity": "N"
  },
  {
    "id": "ch3_09",
    "chapterId": "ch3",
    "chapterName": "食光记·味",
    "seriesId": "food",
    "indexInChapter": 9,
    "difficultyStars": 6,
    "pieceCount": 49,
    "stdTimeSec": 200,
    "shape": "irregular",
    "refMode": "none",
    "rotatable": false,
    "rarity": "N"
  },
  {
    "id": "ch3_10",
    "chapterId": "ch3",
    "chapterName": "食光记·味",
    "seriesId": "food",
    "indexInChapter": 10,
    "difficultyStars": 6,
    "pieceCount": 49,
    "stdTimeSec": 200,
    "shape": "irregular",
    "refMode": "none",
    "rotatable": false,
    "rarity": "N"
  },
  {
    "id": "ch3_11",
    "chapterId": "ch3",
    "chapterName": "食光记·味",
    "seriesId": "food",
    "indexInChapter": 11,
    "difficultyStars": 6,
    "pieceCount": 49,
    "stdTimeSec": 200,
    "shape": "irregular",
    "refMode": "none",
    "rotatable": false,
    "rarity": "N"
  },
  {
    "id": "ch3_12",
    "chapterId": "ch3",
    "chapterName": "食光记·味",
    "seriesId": "food",
    "indexInChapter": 12,
    "difficultyStars": 6,
    "pieceCount": 49,
    "stdTimeSec": 200,
    "shape": "irregular",
    "refMode": "none",
    "rotatable": false,
    "rarity": "N"
  },
  {
    "id": "ch4_01",
    "chapterId": "ch4",
    "chapterName": "山河卷·远",
    "seriesId": "landscape",
    "indexInChapter": 1,
    "difficultyStars": 7,
    "pieceCount": 64,
    "stdTimeSec": 260,
    "shape": "irregular",
    "refMode": "none",
    "rotatable": false,
    "rarity": "N"
  },
  {
    "id": "ch4_02",
    "chapterId": "ch4",
    "chapterName": "山河卷·远",
    "seriesId": "landscape",
    "indexInChapter": 2,
    "difficultyStars": 7,
    "pieceCount": 64,
    "stdTimeSec": 260,
    "shape": "irregular",
    "refMode": "none",
    "rotatable": false,
    "rarity": "N"
  },
  {
    "id": "ch4_03",
    "chapterId": "ch4",
    "chapterName": "山河卷·远",
    "seriesId": "landscape",
    "indexInChapter": 3,
    "difficultyStars": 7,
    "pieceCount": 64,
    "stdTimeSec": 260,
    "shape": "irregular",
    "refMode": "none",
    "rotatable": false,
    "rarity": "N"
  },
  {
    "id": "ch4_04",
    "chapterId": "ch4",
    "chapterName": "山河卷·远",
    "seriesId": "landscape",
    "indexInChapter": 4,
    "difficultyStars": 7,
    "pieceCount": 64,
    "stdTimeSec": 260,
    "shape": "irregular",
    "refMode": "none",
    "rotatable": false,
    "rarity": "N"
  },
  {
    "id": "ch4_05",
    "chapterId": "ch4",
    "chapterName": "山河卷·远",
    "seriesId": "landscape",
    "indexInChapter": 5,
    "difficultyStars": 7,
    "pieceCount": 64,
    "stdTimeSec": 260,
    "shape": "irregular",
    "refMode": "none",
    "rotatable": false,
    "rarity": "N"
  },
  {
    "id": "ch4_06",
    "chapterId": "ch4",
    "chapterName": "山河卷·远",
    "seriesId": "landscape",
    "indexInChapter": 6,
    "difficultyStars": 7,
    "pieceCount": 64,
    "stdTimeSec": 260,
    "shape": "irregular",
    "refMode": "none",
    "rotatable": false,
    "rarity": "N"
  },
  {
    "id": "ch4_07",
    "chapterId": "ch4",
    "chapterName": "山河卷·远",
    "seriesId": "landscape",
    "indexInChapter": 7,
    "difficultyStars": 8,
    "pieceCount": 81,
    "stdTimeSec": 330,
    "shape": "irregular",
    "refMode": "none",
    "rotatable": false,
    "rarity": "N"
  },
  {
    "id": "ch4_08",
    "chapterId": "ch4",
    "chapterName": "山河卷·远",
    "seriesId": "landscape",
    "indexInChapter": 8,
    "difficultyStars": 8,
    "pieceCount": 81,
    "stdTimeSec": 330,
    "shape": "irregular",
    "refMode": "none",
    "rotatable": false,
    "rarity": "N"
  },
  {
    "id": "ch4_09",
    "chapterId": "ch4",
    "chapterName": "山河卷·远",
    "seriesId": "landscape",
    "indexInChapter": 9,
    "difficultyStars": 8,
    "pieceCount": 81,
    "stdTimeSec": 330,
    "shape": "irregular",
    "refMode": "none",
    "rotatable": false,
    "rarity": "N"
  },
  {
    "id": "ch4_10",
    "chapterId": "ch4",
    "chapterName": "山河卷·远",
    "seriesId": "landscape",
    "indexInChapter": 10,
    "difficultyStars": 8,
    "pieceCount": 81,
    "stdTimeSec": 330,
    "shape": "irregular",
    "refMode": "none",
    "rotatable": false,
    "rarity": "N"
  },
  {
    "id": "ch4_11",
    "chapterId": "ch4",
    "chapterName": "山河卷·远",
    "seriesId": "landscape",
    "indexInChapter": 11,
    "difficultyStars": 8,
    "pieceCount": 81,
    "stdTimeSec": 330,
    "shape": "irregular",
    "refMode": "none",
    "rotatable": false,
    "rarity": "N"
  },
  {
    "id": "ch4_12",
    "chapterId": "ch4",
    "chapterName": "山河卷·远",
    "seriesId": "landscape",
    "indexInChapter": 12,
    "difficultyStars": 8,
    "pieceCount": 81,
    "stdTimeSec": 330,
    "shape": "irregular",
    "refMode": "none",
    "rotatable": false,
    "rarity": "N"
  },
  {
    "id": "ch5_01",
    "chapterId": "ch5",
    "chapterName": "星辰谱·幻",
    "seriesId": "star",
    "indexInChapter": 1,
    "difficultyStars": 9,
    "pieceCount": 100,
    "stdTimeSec": 410,
    "shape": "irregular",
    "refMode": "none",
    "rotatable": true,
    "rarity": "N"
  },
  {
    "id": "ch5_02",
    "chapterId": "ch5",
    "chapterName": "星辰谱·幻",
    "seriesId": "star",
    "indexInChapter": 2,
    "difficultyStars": 9,
    "pieceCount": 100,
    "stdTimeSec": 410,
    "shape": "irregular",
    "refMode": "none",
    "rotatable": true,
    "rarity": "N"
  },
  {
    "id": "ch5_03",
    "chapterId": "ch5",
    "chapterName": "星辰谱·幻",
    "seriesId": "star",
    "indexInChapter": 3,
    "difficultyStars": 9,
    "pieceCount": 100,
    "stdTimeSec": 410,
    "shape": "irregular",
    "refMode": "none",
    "rotatable": true,
    "rarity": "N"
  },
  {
    "id": "ch5_04",
    "chapterId": "ch5",
    "chapterName": "星辰谱·幻",
    "seriesId": "star",
    "indexInChapter": 4,
    "difficultyStars": 9,
    "pieceCount": 100,
    "stdTimeSec": 410,
    "shape": "irregular",
    "refMode": "none",
    "rotatable": true,
    "rarity": "N"
  },
  {
    "id": "ch5_05",
    "chapterId": "ch5",
    "chapterName": "星辰谱·幻",
    "seriesId": "star",
    "indexInChapter": 5,
    "difficultyStars": 9,
    "pieceCount": 100,
    "stdTimeSec": 410,
    "shape": "irregular",
    "refMode": "none",
    "rotatable": true,
    "rarity": "N"
  },
  {
    "id": "ch5_06",
    "chapterId": "ch5",
    "chapterName": "星辰谱·幻",
    "seriesId": "star",
    "indexInChapter": 6,
    "difficultyStars": 9,
    "pieceCount": 100,
    "stdTimeSec": 410,
    "shape": "irregular",
    "refMode": "none",
    "rotatable": true,
    "rarity": "N"
  },
  {
    "id": "ch5_07",
    "chapterId": "ch5",
    "chapterName": "星辰谱·幻",
    "seriesId": "star",
    "indexInChapter": 7,
    "difficultyStars": 10,
    "pieceCount": 144,
    "stdTimeSec": 600,
    "shape": "irregular",
    "refMode": "none",
    "rotatable": true,
    "rarity": "N"
  },
  {
    "id": "ch5_08",
    "chapterId": "ch5",
    "chapterName": "星辰谱·幻",
    "seriesId": "star",
    "indexInChapter": 8,
    "difficultyStars": 10,
    "pieceCount": 144,
    "stdTimeSec": 600,
    "shape": "irregular",
    "refMode": "none",
    "rotatable": true,
    "rarity": "N"
  },
  {
    "id": "ch5_09",
    "chapterId": "ch5",
    "chapterName": "星辰谱·幻",
    "seriesId": "star",
    "indexInChapter": 9,
    "difficultyStars": 10,
    "pieceCount": 144,
    "stdTimeSec": 600,
    "shape": "irregular",
    "refMode": "none",
    "rotatable": true,
    "rarity": "N"
  },
  {
    "id": "ch5_10",
    "chapterId": "ch5",
    "chapterName": "星辰谱·幻",
    "seriesId": "star",
    "indexInChapter": 10,
    "difficultyStars": 10,
    "pieceCount": 144,
    "stdTimeSec": 600,
    "shape": "irregular",
    "refMode": "none",
    "rotatable": true,
    "rarity": "N"
  },
  {
    "id": "ch5_11",
    "chapterId": "ch5",
    "chapterName": "星辰谱·幻",
    "seriesId": "star",
    "indexInChapter": 11,
    "difficultyStars": 10,
    "pieceCount": 144,
    "stdTimeSec": 600,
    "shape": "irregular",
    "refMode": "none",
    "rotatable": true,
    "rarity": "N"
  },
  {
    "id": "ch5_12",
    "chapterId": "ch5",
    "chapterName": "星辰谱·幻",
    "seriesId": "star",
    "indexInChapter": 12,
    "difficultyStars": 10,
    "pieceCount": 144,
    "stdTimeSec": 600,
    "shape": "irregular",
    "refMode": "none",
    "rotatable": true,
    "rarity": "N"
  }
] as const;

export const DEFAULT_CARDS = [
  {
    "id": "flower_001",
    "seriesId": "flower",
    "seriesName": "花语集",
    "name": "玫瑰",
    "rarity": "N",
    "baseScore": 10,
    "hidden": false,
    "description": "玫瑰 · 普通",
    "image": "images/cards/flower_001.png"
  },
  {
    "id": "flower_002",
    "seriesId": "flower",
    "seriesName": "花语集",
    "name": "郁金香",
    "rarity": "N",
    "baseScore": 10,
    "hidden": false,
    "description": "郁金香 · 普通",
    "image": "images/cards/flower_002.png"
  },
  {
    "id": "flower_003",
    "seriesId": "flower",
    "seriesName": "花语集",
    "name": "百合",
    "rarity": "N",
    "baseScore": 10,
    "hidden": false,
    "description": "百合 · 普通",
    "image": "images/cards/flower_003.png"
  },
  {
    "id": "flower_004",
    "seriesId": "flower",
    "seriesName": "花语集",
    "name": "向日葵",
    "rarity": "N",
    "baseScore": 10,
    "hidden": false,
    "description": "向日葵 · 普通",
    "image": "images/cards/flower_004.png"
  },
  {
    "id": "flower_005",
    "seriesId": "flower",
    "seriesName": "花语集",
    "name": "樱花",
    "rarity": "N",
    "baseScore": 10,
    "hidden": false,
    "description": "樱花 · 普通",
    "image": "images/cards/flower_005.png"
  },
  {
    "id": "flower_006",
    "seriesId": "flower",
    "seriesName": "花语集",
    "name": "薰衣草",
    "rarity": "R",
    "baseScore": 30,
    "hidden": false,
    "description": "薰衣草 · 稀有",
    "image": "images/cards/flower_006.png"
  },
  {
    "id": "flower_007",
    "seriesId": "flower",
    "seriesName": "花语集",
    "name": "牡丹",
    "rarity": "R",
    "baseScore": 30,
    "hidden": false,
    "description": "牡丹 · 稀有",
    "image": "images/cards/flower_007.png"
  },
  {
    "id": "flower_008",
    "seriesId": "flower",
    "seriesName": "花语集",
    "name": "雏菊",
    "rarity": "R",
    "baseScore": 30,
    "hidden": false,
    "description": "雏菊 · 稀有",
    "image": "images/cards/flower_008.png"
  },
  {
    "id": "flower_009",
    "seriesId": "flower",
    "seriesName": "花语集",
    "name": "风信子",
    "rarity": "R",
    "baseScore": 30,
    "hidden": false,
    "description": "风信子 · 稀有",
    "image": "images/cards/flower_009.png"
  },
  {
    "id": "flower_010",
    "seriesId": "flower",
    "seriesName": "花语集",
    "name": "茉莉",
    "rarity": "SR",
    "baseScore": 80,
    "hidden": false,
    "description": "茉莉 · 超稀有",
    "image": "images/cards/flower_010.png"
  },
  {
    "id": "flower_011",
    "seriesId": "flower",
    "seriesName": "花语集",
    "name": "鸢尾",
    "rarity": "SR",
    "baseScore": 80,
    "hidden": false,
    "description": "鸢尾 · 超稀有",
    "image": "images/cards/flower_011.png"
  },
  {
    "id": "flower_012",
    "seriesId": "flower",
    "seriesName": "花语集",
    "name": "芙蓉",
    "rarity": "SSR",
    "baseScore": 200,
    "hidden": false,
    "description": "芙蓉 · 传说",
    "image": "images/cards/flower_012.png"
  },
  {
    "id": "flower_H01",
    "seriesId": "flower",
    "seriesName": "花语集",
    "name": "花语集·秘",
    "rarity": "HIDDEN",
    "baseScore": 300,
    "hidden": true,
    "description": "隐藏卡，仅特殊条件获得",
    "image": "images/cards/flower_H01.png"
  },
  {
    "id": "pet_001",
    "seriesId": "pet",
    "seriesName": "萌宠志",
    "name": "柴犬",
    "rarity": "N",
    "baseScore": 10,
    "hidden": false,
    "description": "柴犬 · 普通",
    "image": "images/cards/pet_001.png"
  },
  {
    "id": "pet_002",
    "seriesId": "pet",
    "seriesName": "萌宠志",
    "name": "布偶猫",
    "rarity": "N",
    "baseScore": 10,
    "hidden": false,
    "description": "布偶猫 · 普通",
    "image": "images/cards/pet_002.png"
  },
  {
    "id": "pet_003",
    "seriesId": "pet",
    "seriesName": "萌宠志",
    "name": "柯基",
    "rarity": "N",
    "baseScore": 10,
    "hidden": false,
    "description": "柯基 · 普通",
    "image": "images/cards/pet_003.png"
  },
  {
    "id": "pet_004",
    "seriesId": "pet",
    "seriesName": "萌宠志",
    "name": "金毛",
    "rarity": "N",
    "baseScore": 10,
    "hidden": false,
    "description": "金毛 · 普通",
    "image": "images/cards/pet_004.png"
  },
  {
    "id": "pet_005",
    "seriesId": "pet",
    "seriesName": "萌宠志",
    "name": "仓鼠",
    "rarity": "N",
    "baseScore": 10,
    "hidden": false,
    "description": "仓鼠 · 普通",
    "image": "images/cards/pet_005.png"
  },
  {
    "id": "pet_006",
    "seriesId": "pet",
    "seriesName": "萌宠志",
    "name": "垂耳兔",
    "rarity": "N",
    "baseScore": 10,
    "hidden": false,
    "description": "垂耳兔 · 普通",
    "image": "images/cards/pet_006.png"
  },
  {
    "id": "pet_007",
    "seriesId": "pet",
    "seriesName": "萌宠志",
    "name": "鹦鹉",
    "rarity": "N",
    "baseScore": 10,
    "hidden": false,
    "description": "鹦鹉 · 普通",
    "image": "images/cards/pet_007.png"
  },
  {
    "id": "pet_008",
    "seriesId": "pet",
    "seriesName": "萌宠志",
    "name": "刺猬",
    "rarity": "R",
    "baseScore": 30,
    "hidden": false,
    "description": "刺猬 · 稀有",
    "image": "images/cards/pet_008.png"
  },
  {
    "id": "pet_009",
    "seriesId": "pet",
    "seriesName": "萌宠志",
    "name": "龙猫",
    "rarity": "R",
    "baseScore": 30,
    "hidden": false,
    "description": "龙猫 · 稀有",
    "image": "images/cards/pet_009.png"
  },
  {
    "id": "pet_010",
    "seriesId": "pet",
    "seriesName": "萌宠志",
    "name": "橘猫",
    "rarity": "R",
    "baseScore": 30,
    "hidden": false,
    "description": "橘猫 · 稀有",
    "image": "images/cards/pet_010.png"
  },
  {
    "id": "pet_011",
    "seriesId": "pet",
    "seriesName": "萌宠志",
    "name": "萨摩耶",
    "rarity": "R",
    "baseScore": 30,
    "hidden": false,
    "description": "萨摩耶 · 稀有",
    "image": "images/cards/pet_011.png"
  },
  {
    "id": "pet_012",
    "seriesId": "pet",
    "seriesName": "萌宠志",
    "name": "豚鼠",
    "rarity": "R",
    "baseScore": 30,
    "hidden": false,
    "description": "豚鼠 · 稀有",
    "image": "images/cards/pet_012.png"
  },
  {
    "id": "pet_013",
    "seriesId": "pet",
    "seriesName": "萌宠志",
    "name": "水獭",
    "rarity": "SR",
    "baseScore": 80,
    "hidden": false,
    "description": "水獭 · 超稀有",
    "image": "images/cards/pet_013.png"
  },
  {
    "id": "pet_014",
    "seriesId": "pet",
    "seriesName": "萌宠志",
    "name": "狐狸",
    "rarity": "SR",
    "baseScore": 80,
    "hidden": false,
    "description": "狐狸 · 超稀有",
    "image": "images/cards/pet_014.png"
  },
  {
    "id": "pet_015",
    "seriesId": "pet",
    "seriesName": "萌宠志",
    "name": "企鹅",
    "rarity": "SR",
    "baseScore": 80,
    "hidden": false,
    "description": "企鹅 · 超稀有",
    "image": "images/cards/pet_015.png"
  },
  {
    "id": "pet_016",
    "seriesId": "pet",
    "seriesName": "萌宠志",
    "name": "羊驼",
    "rarity": "SSR",
    "baseScore": 200,
    "hidden": false,
    "description": "羊驼 · 传说",
    "image": "images/cards/pet_016.png"
  },
  {
    "id": "pet_H01",
    "seriesId": "pet",
    "seriesName": "萌宠志",
    "name": "萌宠志·秘",
    "rarity": "HIDDEN",
    "baseScore": 300,
    "hidden": true,
    "description": "隐藏卡，仅特殊条件获得",
    "image": "images/cards/pet_H01.png"
  },
  {
    "id": "food_001",
    "seriesId": "food",
    "seriesName": "食光记",
    "name": "拉面",
    "rarity": "N",
    "baseScore": 10,
    "hidden": false,
    "description": "拉面 · 普通",
    "image": "images/cards/food_001.png"
  },
  {
    "id": "food_002",
    "seriesId": "food",
    "seriesName": "食光记",
    "name": "寿司",
    "rarity": "N",
    "baseScore": 10,
    "hidden": false,
    "description": "寿司 · 普通",
    "image": "images/cards/food_002.png"
  },
  {
    "id": "food_003",
    "seriesId": "food",
    "seriesName": "食光记",
    "name": "蛋糕",
    "rarity": "N",
    "baseScore": 10,
    "hidden": false,
    "description": "蛋糕 · 普通",
    "image": "images/cards/food_003.png"
  },
  {
    "id": "food_004",
    "seriesId": "food",
    "seriesName": "食光记",
    "name": "奶茶",
    "rarity": "N",
    "baseScore": 10,
    "hidden": false,
    "description": "奶茶 · 普通",
    "image": "images/cards/food_004.png"
  },
  {
    "id": "food_005",
    "seriesId": "food",
    "seriesName": "食光记",
    "name": "火锅",
    "rarity": "N",
    "baseScore": 10,
    "hidden": false,
    "description": "火锅 · 普通",
    "image": "images/cards/food_005.png"
  },
  {
    "id": "food_006",
    "seriesId": "food",
    "seriesName": "食光记",
    "name": "烧烤",
    "rarity": "N",
    "baseScore": 10,
    "hidden": false,
    "description": "烧烤 · 普通",
    "image": "images/cards/food_006.png"
  },
  {
    "id": "food_007",
    "seriesId": "food",
    "seriesName": "食光记",
    "name": "披萨",
    "rarity": "N",
    "baseScore": 10,
    "hidden": false,
    "description": "披萨 · 普通",
    "image": "images/cards/food_007.png"
  },
  {
    "id": "food_008",
    "seriesId": "food",
    "seriesName": "食光记",
    "name": "冰淇淋",
    "rarity": "R",
    "baseScore": 30,
    "hidden": false,
    "description": "冰淇淋 · 稀有",
    "image": "images/cards/food_008.png"
  },
  {
    "id": "food_009",
    "seriesId": "food",
    "seriesName": "食光记",
    "name": "包子",
    "rarity": "R",
    "baseScore": 30,
    "hidden": false,
    "description": "包子 · 稀有",
    "image": "images/cards/food_009.png"
  },
  {
    "id": "food_010",
    "seriesId": "food",
    "seriesName": "食光记",
    "name": "煎饼",
    "rarity": "R",
    "baseScore": 30,
    "hidden": false,
    "description": "煎饼 · 稀有",
    "image": "images/cards/food_010.png"
  },
  {
    "id": "food_011",
    "seriesId": "food",
    "seriesName": "食光记",
    "name": "牛排",
    "rarity": "R",
    "baseScore": 30,
    "hidden": false,
    "description": "牛排 · 稀有",
    "image": "images/cards/food_011.png"
  },
  {
    "id": "food_012",
    "seriesId": "food",
    "seriesName": "食光记",
    "name": "甜甜圈",
    "rarity": "R",
    "baseScore": 30,
    "hidden": false,
    "description": "甜甜圈 · 稀有",
    "image": "images/cards/food_012.png"
  },
  {
    "id": "food_013",
    "seriesId": "food",
    "seriesName": "食光记",
    "name": "咖喱",
    "rarity": "SR",
    "baseScore": 80,
    "hidden": false,
    "description": "咖喱 · 超稀有",
    "image": "images/cards/food_013.png"
  },
  {
    "id": "food_014",
    "seriesId": "food",
    "seriesName": "食光记",
    "name": "麻薯",
    "rarity": "SR",
    "baseScore": 80,
    "hidden": false,
    "description": "麻薯 · 超稀有",
    "image": "images/cards/food_014.png"
  },
  {
    "id": "food_015",
    "seriesId": "food",
    "seriesName": "食光记",
    "name": "可丽饼",
    "rarity": "SR",
    "baseScore": 80,
    "hidden": false,
    "description": "可丽饼 · 超稀有",
    "image": "images/cards/food_015.png"
  },
  {
    "id": "food_016",
    "seriesId": "food",
    "seriesName": "食光记",
    "name": "关东煮",
    "rarity": "SSR",
    "baseScore": 200,
    "hidden": false,
    "description": "关东煮 · 传说",
    "image": "images/cards/food_016.png"
  },
  {
    "id": "food_H01",
    "seriesId": "food",
    "seriesName": "食光记",
    "name": "食光记·秘",
    "rarity": "HIDDEN",
    "baseScore": 300,
    "hidden": true,
    "description": "隐藏卡，仅特殊条件获得",
    "image": "images/cards/food_H01.png"
  },
  {
    "id": "landscape_001",
    "seriesId": "landscape",
    "seriesName": "山河卷",
    "name": "长城",
    "rarity": "N",
    "baseScore": 10,
    "hidden": false,
    "description": "长城 · 普通",
    "image": "images/cards/landscape_001.png"
  },
  {
    "id": "landscape_002",
    "seriesId": "landscape",
    "seriesName": "山河卷",
    "name": "西湖",
    "rarity": "N",
    "baseScore": 10,
    "hidden": false,
    "description": "西湖 · 普通",
    "image": "images/cards/landscape_002.png"
  },
  {
    "id": "landscape_003",
    "seriesId": "landscape",
    "seriesName": "山河卷",
    "name": "黄山",
    "rarity": "N",
    "baseScore": 10,
    "hidden": false,
    "description": "黄山 · 普通",
    "image": "images/cards/landscape_003.png"
  },
  {
    "id": "landscape_004",
    "seriesId": "landscape",
    "seriesName": "山河卷",
    "name": "故宫",
    "rarity": "N",
    "baseScore": 10,
    "hidden": false,
    "description": "故宫 · 普通",
    "image": "images/cards/landscape_004.png"
  },
  {
    "id": "landscape_005",
    "seriesId": "landscape",
    "seriesName": "山河卷",
    "name": "漓江",
    "rarity": "R",
    "baseScore": 30,
    "hidden": false,
    "description": "漓江 · 稀有",
    "image": "images/cards/landscape_005.png"
  },
  {
    "id": "landscape_006",
    "seriesId": "landscape",
    "seriesName": "山河卷",
    "name": "张家界",
    "rarity": "R",
    "baseScore": 30,
    "hidden": false,
    "description": "张家界 · 稀有",
    "image": "images/cards/landscape_006.png"
  },
  {
    "id": "landscape_007",
    "seriesId": "landscape",
    "seriesName": "山河卷",
    "name": "鼓浪屿",
    "rarity": "R",
    "baseScore": 30,
    "hidden": false,
    "description": "鼓浪屿 · 稀有",
    "image": "images/cards/landscape_007.png"
  },
  {
    "id": "landscape_008",
    "seriesId": "landscape",
    "seriesName": "山河卷",
    "name": "洱海",
    "rarity": "R",
    "baseScore": 30,
    "hidden": false,
    "description": "洱海 · 稀有",
    "image": "images/cards/landscape_008.png"
  },
  {
    "id": "landscape_009",
    "seriesId": "landscape",
    "seriesName": "山河卷",
    "name": "泰山",
    "rarity": "SR",
    "baseScore": 80,
    "hidden": false,
    "description": "泰山 · 超稀有",
    "image": "images/cards/landscape_009.png"
  },
  {
    "id": "landscape_010",
    "seriesId": "landscape",
    "seriesName": "山河卷",
    "name": "九寨沟",
    "rarity": "SR",
    "baseScore": 80,
    "hidden": false,
    "description": "九寨沟 · 超稀有",
    "image": "images/cards/landscape_010.png"
  },
  {
    "id": "landscape_011",
    "seriesId": "landscape",
    "seriesName": "山河卷",
    "name": "布达拉宫",
    "rarity": "SR",
    "baseScore": 80,
    "hidden": false,
    "description": "布达拉宫 · 超稀有",
    "image": "images/cards/landscape_011.png"
  },
  {
    "id": "landscape_012",
    "seriesId": "landscape",
    "seriesName": "山河卷",
    "name": "壶口瀑布",
    "rarity": "SSR",
    "baseScore": 200,
    "hidden": false,
    "description": "壶口瀑布 · 传说",
    "image": "images/cards/landscape_012.png"
  },
  {
    "id": "landscape_H01",
    "seriesId": "landscape",
    "seriesName": "山河卷",
    "name": "山河卷·秘",
    "rarity": "HIDDEN",
    "baseScore": 300,
    "hidden": true,
    "description": "隐藏卡，仅特殊条件获得",
    "image": "images/cards/landscape_H01.png"
  },
  {
    "id": "star_001",
    "seriesId": "star",
    "seriesName": "星辰谱",
    "name": "白羊",
    "rarity": "N",
    "baseScore": 10,
    "hidden": false,
    "description": "白羊 · 普通",
    "image": "images/cards/star_001.png"
  },
  {
    "id": "star_002",
    "seriesId": "star",
    "seriesName": "星辰谱",
    "name": "金牛",
    "rarity": "N",
    "baseScore": 10,
    "hidden": false,
    "description": "金牛 · 普通",
    "image": "images/cards/star_002.png"
  },
  {
    "id": "star_003",
    "seriesId": "star",
    "seriesName": "星辰谱",
    "name": "双子",
    "rarity": "N",
    "baseScore": 10,
    "hidden": false,
    "description": "双子 · 普通",
    "image": "images/cards/star_003.png"
  },
  {
    "id": "star_004",
    "seriesId": "star",
    "seriesName": "星辰谱",
    "name": "巨蟹",
    "rarity": "N",
    "baseScore": 10,
    "hidden": false,
    "description": "巨蟹 · 普通",
    "image": "images/cards/star_004.png"
  },
  {
    "id": "star_005",
    "seriesId": "star",
    "seriesName": "星辰谱",
    "name": "狮子",
    "rarity": "R",
    "baseScore": 30,
    "hidden": false,
    "description": "狮子 · 稀有",
    "image": "images/cards/star_005.png"
  },
  {
    "id": "star_006",
    "seriesId": "star",
    "seriesName": "星辰谱",
    "name": "处女",
    "rarity": "R",
    "baseScore": 30,
    "hidden": false,
    "description": "处女 · 稀有",
    "image": "images/cards/star_006.png"
  },
  {
    "id": "star_007",
    "seriesId": "star",
    "seriesName": "星辰谱",
    "name": "天秤",
    "rarity": "R",
    "baseScore": 30,
    "hidden": false,
    "description": "天秤 · 稀有",
    "image": "images/cards/star_007.png"
  },
  {
    "id": "star_008",
    "seriesId": "star",
    "seriesName": "星辰谱",
    "name": "天蝎",
    "rarity": "R",
    "baseScore": 30,
    "hidden": false,
    "description": "天蝎 · 稀有",
    "image": "images/cards/star_008.png"
  },
  {
    "id": "star_009",
    "seriesId": "star",
    "seriesName": "星辰谱",
    "name": "射手",
    "rarity": "SR",
    "baseScore": 80,
    "hidden": false,
    "description": "射手 · 超稀有",
    "image": "images/cards/star_009.png"
  },
  {
    "id": "star_010",
    "seriesId": "star",
    "seriesName": "星辰谱",
    "name": "摩羯",
    "rarity": "SR",
    "baseScore": 80,
    "hidden": false,
    "description": "摩羯 · 超稀有",
    "image": "images/cards/star_010.png"
  },
  {
    "id": "star_011",
    "seriesId": "star",
    "seriesName": "星辰谱",
    "name": "水瓶",
    "rarity": "SR",
    "baseScore": 80,
    "hidden": false,
    "description": "水瓶 · 超稀有",
    "image": "images/cards/star_011.png"
  },
  {
    "id": "star_012",
    "seriesId": "star",
    "seriesName": "星辰谱",
    "name": "双鱼",
    "rarity": "SSR",
    "baseScore": 200,
    "hidden": false,
    "description": "双鱼 · 传说",
    "image": "images/cards/star_012.png"
  },
  {
    "id": "star_H01",
    "seriesId": "star",
    "seriesName": "星辰谱",
    "name": "星辰谱·秘",
    "rarity": "HIDDEN",
    "baseScore": 300,
    "hidden": true,
    "description": "隐藏卡，仅特殊条件获得",
    "image": "images/cards/star_H01.png"
  }
] as const;

export const DEFAULT_DIFFICULTY = [
  {
    "stars": 1,
    "pieceCount": 4,
    "shape": "rect",
    "refMode": "always",
    "stdTimeSec": 30,
    "timeLimitSec": 0,
    "distractors": 0,
    "rotatable": false
  },
  {
    "stars": 2,
    "pieceCount": 9,
    "shape": "rect",
    "refMode": "first5s",
    "stdTimeSec": 60,
    "timeLimitSec": 0,
    "distractors": 0,
    "rotatable": false
  },
  {
    "stars": 3,
    "pieceCount": 16,
    "shape": "rounded",
    "refMode": "first5s",
    "stdTimeSec": 90,
    "timeLimitSec": 0,
    "distractors": 1,
    "rotatable": false
  },
  {
    "stars": 4,
    "pieceCount": 25,
    "shape": "rounded",
    "refMode": "none",
    "stdTimeSec": 120,
    "timeLimitSec": 180,
    "distractors": 2,
    "rotatable": false
  },
  {
    "stars": 5,
    "pieceCount": 36,
    "shape": "rounded",
    "refMode": "none",
    "stdTimeSec": 150,
    "timeLimitSec": 150,
    "distractors": 3,
    "rotatable": false
  },
  {
    "stars": 6,
    "pieceCount": 49,
    "shape": "irregular",
    "refMode": "none",
    "stdTimeSec": 200,
    "timeLimitSec": 120,
    "distractors": 3,
    "rotatable": false
  },
  {
    "stars": 7,
    "pieceCount": 64,
    "shape": "irregular",
    "refMode": "none",
    "stdTimeSec": 260,
    "timeLimitSec": 120,
    "distractors": 4,
    "rotatable": false
  },
  {
    "stars": 8,
    "pieceCount": 81,
    "shape": "irregular",
    "refMode": "none",
    "stdTimeSec": 330,
    "timeLimitSec": 100,
    "distractors": 4,
    "rotatable": false
  },
  {
    "stars": 9,
    "pieceCount": 100,
    "shape": "irregular",
    "refMode": "none",
    "stdTimeSec": 410,
    "timeLimitSec": 90,
    "distractors": 5,
    "rotatable": true
  },
  {
    "stars": 10,
    "pieceCount": 144,
    "shape": "irregular",
    "refMode": "none",
    "stdTimeSec": 600,
    "timeLimitSec": 90,
    "distractors": 6,
    "rotatable": true
  }
] as const;

export interface GameConfig {
  levels: typeof DEFAULT_LEVELS;
  cards: typeof DEFAULT_CARDS;
  difficulty: typeof DEFAULT_DIFFICULTY;
}

export function getDefaultConfig(): GameConfig {
  return {
    levels: DEFAULT_LEVELS as any,
    cards: DEFAULT_CARDS as any,
    difficulty: DEFAULT_DIFFICULTY as any,
  };
}
